<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UP2kc</name>
   <tag></tag>
   <elementGuidId>1321d070-c2e5-41e3-a09e-4b4249b19c10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UP2kc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#UP2kc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>232aa5f3-1fca-4612-b36c-1646a9b41fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelRole</value>
      <webElementGuid>c08ae359-635f-4d46-9ece-b51a0bc15d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UP2kc</value>
      <webElementGuid>a63278eb-7665-42ab-8adb-e405da7604c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UP2kc</value>
      <webElementGuid>02561d66-0799-4e6e-902c-091c30b280d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>114b2ac3-092a-4229-9dc4-5b7fa2864cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UP2kc&quot;)</value>
      <webElementGuid>e392ac98-167a-4957-8047-e6f2728a6270</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UP2kc']</value>
      <webElementGuid>61414634-dd66-4ad2-ac06-9b61279b8c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2502a4f0-1be4-4c3c-8f1d-8fa038d24d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UP2kc' and @name = 'UP2kc']</value>
      <webElementGuid>2b6480d2-21d3-44c9-8fe9-a4eb9ff22eeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
