<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Start</name>
   <tag></tag>
   <elementGuidId>f2f4fdb4-d95b-481c-8b30-57f2044b76b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.waves-effect.col.s12.m12.l12.btn-large.uiColorButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b88a143f-feaa-4ffc-a898-4a6749ab1d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>waves-effect col s12 m12 l12 btn-large uiColorButton</value>
      <webElementGuid>7972b045-f926-4c74-a6a2-63305d46b91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start</value>
      <webElementGuid>0da9900a-203d-4c5d-b7c6-674f75034871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;body row1 scroll-y&quot;]/app-rpa1[1]/div[@class=&quot;row parent&quot;]/div[@class=&quot;instructions col s3 m3 l3 uiColorSecondary&quot;]/div[6]/button[@class=&quot;waves-effect col s12 m12 l12 btn-large uiColorButton&quot;]</value>
      <webElementGuid>cd5f07d4-2df6-4853-acd4-2bc34e06d91e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f7dba6b8-9792-415b-9541-bdc570ff775f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Start' or . = 'Start')]</value>
      <webElementGuid>9ced773b-da74-496d-8eb0-52ef8a43e9fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
